# Generated by Django 3.1.7 on 2021-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200316_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=200, null=True)),
                ('Employee_department', models.CharField(max_length=50)),
                ('number_absences', models.IntegerField()),
                ('number_overtime', models.IntegerField()),
                ('years_of_work', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course_Taken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
